version: '3.9'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    container_name: mssql_server
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=P@ssw0rd
      - DEBUG=1
    volumes:
      - mssql_data:/var/opt/mssql
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  mssql_data: